[project]
name = "renogy-ha"
version = "0.7.1"
description = "Home Assisstant integration for Renogy devices"
readme = "README.md"
requires-python = ">=3.14.2"
dependencies = [
    "homeassistant>=2026.4.4",
    "renogy-ble==2.3.1",
]

[dependency-groups]
dev = [
    "pytest>=9.0.3",
    "pytest-asyncio>=1.4.0",
    "ruff>=0.15.12",
    "ty==0.0.32",
]

[tool.pytest.ini_options]
pythonpath = ["."]
markers = [
    "asyncio: mark test as an asyncio coroutine",
]
asyncio_default_fixture_loop_scope = "function"

[tool.ruff]
line-length = 88
target-version = "py314"

[tool.ruff.lint]
select = ["I", "E", "F"]  # I = isort, E = pycodestyle, F = pyflakes

[tool.ruff.format]
quote-style = "double"
